require:
  - rubocop-performance
  - rubocop-rails

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  AllowedMethods:
    - namespace

Metrics/ClassLength:
  CountAsOne:
    - array
    - hash
    - method_call