apiVersion: v1
kind: Service
metadata:
  name: {{ include "quantu-server.fullname" . }}
  labels: {{- include "quantu-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "quantu-server.selectorLabels" . | nindent 4 }}
