replicas:
  min: 1
  max: 4
  resource:
    cpu:
      utilization: 60

image:
  repository: ghcr.io/quantu-app/quantu-server
  pullPolicy: Always
  hash: sha256:2af310fac13872efeed20df46547f19616fecab261e1dd0a23bc63c5b75ad30f

env:
  JWT_EXPIRES_AT: "604800"

ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: 'true'
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/secure-backends: 'true'
  hosts:
    - host: api.quantu.app
      paths:
        - /
  tls:
    - secretName: quantu-app-quantu-server-tls
      hosts:
        - api.quantu.app

resources:
  requests:
    cpu: 100m
    memory: 100M
  limits:
    cpu: 500m
    memory: 500M
