name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: 'Ruby 3.1 / PostgreSQL 14.6'
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:14.6
        env:
          POSTGRES_DB: quantu_server_test
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
          bundler-cache: true

      - name: Install required apt packages
        run: |
          sudo apt-get -y install libpq-dev
      
      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4

      - name: Run tests with RSpec
        env:
          SECRET_KEY: f6b6daea12018f0afc969ea7e88ec38bb6e5441bb9c4e514177756bca36da4cb536ad4b75a87a6136c8bc227ec9598033fd2052bcebc4a9de398cdf218c0c582
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/quantu_server_test
        run: |
          bundle exec rails db:setup
          bundle exec rspec
      
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          flag-name: run-ruby-3.1.2
          parallel: true

  test_finalizer:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
        parallel-finished: true