name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: 'Ruby ${{ matrix.ruby }} / PostgreSQL ${{ matrix.postgres }} / Deps ${{ matrix.dependencies }}'
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:14.6
        env:
          POSTGRES_DB: quantu_server_test
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports: ["5432:5432"]
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/quantu_server_test
      RAILS_ENV: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Run tests
        run: bundle exec rspec